### ISSUE TITLE
似乎不适配  vscode 版本 1.81.0

### ISSUE THREAD

**Issue by hongxiyu** [luqimin/tinylight-vscode#10]
颜色变化了，比如括号变蓝色了

<img width="530" alt="image" src="https://github.com/luqimin/tinylight-vscode/assets/8132101/4180b287-0f5a-47c2-b094-08531f9d2e72">

**Comment by luqimin** [comment]
最近比较忙不太有时间调整 😭

**Comment by luqimin** [comment]
import内的花括号似乎写的颜色不会生效，看了几个其他主题也这样
