### ISSUE TITLE
Ipynb文件的颜色太接近

### ISSUE THREAD

**Issue by YAETHeryk** [luqimin/tinylight-vscode#12]
![image](https://github.com/luqimin/tinylight-vscode/assets/94971073/98c5af03-5e26-47c6-8a5f-e565c3cbb865)

如图，虽然也不是没法看，但是这区分度有点低

**Comment by luqimin** [comment]
近期看看  就import这里颜色区分度有问题吗

**Comment by YAETHeryk** [comment]
> 近期看看 就import这里颜色区分度有问题吗

![image](https://github.com/luqimin/tinylight-vscode/assets/94971073/3ff666ae-9094-4c58-8b9a-fd5ec9773602)

普通py文件也有类似的问题，除了import的包，像range，int，list这种内置函数也是差不多的颜色

**Comment by luqimin** [comment]
升级插件看看

**Comment by YAETHeryk** [comment]
> 升级插件看看

现在是蓝色的，看起来好多了
