### ISSUE TITLE
在源代码管理的message输入框中选中一段字符没有底色显示

### ISSUE THREAD

**Issue by mmxgqh** [luqimin/tinylight-vscode#14]
Hi, 大佬，
源代码管理框 里，选择(or全选)内容，没有底色。
![image](https://github.com/luqimin/tinylight-vscode/assets/34787434/9b2623f5-f751-49b9-a234-a09305a5619a)

是不是应该跟Ctrl+P里显示的那样才正常：
![image](https://github.com/luqimin/tinylight-vscode/assets/34787434/8351f998-af58-4414-b803-cceae448de47)

**Comment by mmxgqh** [comment]
补充下，这个地方选中也没有底色
![image](https://github.com/luqimin/tinylight-vscode/assets/34787434/ebf690da-21ac-4bba-9ca0-8775990cd865)

**Comment by luqimin** [comment]
升级试试看  v2.0.9

**Comment by mmxgqh** [comment]
OK。 fix by commit d995c9832934cae69f7cb24af2d9b9069c516d88
