### ISSUE TITLE
当我打开终端

### ISSUE THREAD

**Issue by hdmnba** [luqimin/tinylight-vscode#3]
![image](https://user-images.githubusercontent.com/8556433/119425506-1ac80100-bd3a-11eb-8d4a-015fdb15aec7.png)
zhongduan终端还是黑色的，哈哈

**Comment by zackdown** [comment]
This is really uncomfortable .

**Comment by luqimin** [comment]
> ![image](https://user-images.githubusercontent.com/8556433/119425506-1ac80100-bd3a-11eb-8d4a-015fdb15aec7.png)
> zhongduan终端还是黑色的，哈哈

好久没更了哈哈，有时间安排下
当然欢迎pr~~

**Comment by luqimin** [comment]
已更新 v0.8
