### ISSUE TITLE
终端背景白色 然后terminal.ansiBrightWhite也是白色，会看不清楚

### ISSUE THREAD

**Issue by boluo-w0-0w** [luqimin/tinylight-vscode#5]
tinylight-vscode/themes/tiny.json   59行

**Comment by Perino74** [comment]
同遇到此问题，某些字体白色在浅绿背景下几乎完全看不到：
![image](https://user-images.githubusercontent.com/89178251/131358130-ced498b0-a77c-4133-ac4e-c8232b0d1156.png)

**Comment by luqimin** [comment]
@boluo-w0-0w @Perino74 改成了偏黑色
