### ISSUE TITLE
考虑转换到Visual Studio发布一下呢

### ISSUE THREAD

**Issue by ChinaMeidi** [luqimin/tinylight-vscode#7]
https://github.com/microsoft/theme-converter-for-vs

**Comment by Accpfrog** [comment]
转换vscode主题到visual studio的工具

**Comment by Accpfrog** [comment]
https://marketplace.visualstudio.com/items?itemName=accpfrog.TinyLightForVisualStudio
我跟着巨硬教程发布了一版，和您说一下，有几个朋友想要分享一下的。过几天会删除的哈

**Comment by luqimin** [comment]
> 转换vscode主题到visual studio的工具

没用过vs，你可以自己转换玩

**Comment by ChinaMeidi** [comment]
ok
